### ISSUE TITLE
请问一下 bin 文件夹下的是什么文件呀？

### ISSUE THREAD

**Issue by swat199538** [happystraw/auto-picture-matching#1]
为什么这个文件可以实现系统调用呀？求作者解惑。

**Comment by swat199538** [comment]
看了readme 看了看 go的代码， 应该是go的编译文件吧。

**Comment by happystraw** [comment]
`bin/control`是`src/control.go`在**linux**下编译的二进制文件.

这个文件是非必须的. 

如果想使用这个可以按照README中的说明编译成自己需要的平台.

不使用这个的话, 可以通过修改`src/syscall.php`中的调用命令

这个调用的命令是你自己电脑上的第三方软件(需要支持命令行), 一个是截图, 另外一个是模拟点击

**Comment by swat199538** [comment]
感谢。代码挺好的，提供了一下思路。我自己也去实现一个。
